DeploysDevSP2/objects/Claim.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>ClaimEmail__c</fullName>
        <description>Email del asegurado de una reclamación</description>
        <label>ClaimEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstNotificationDateWaitingForDocument__c</fullName>
        <description>Campo que almacena la primera fecha de notificación</description>
        <label>Fecha primer notificación espera docs</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastNotificationDateWaitingForDocument__c</fullName>
        <description>Campo que se crea para almacenar la ultima fecha de notificación de envió de correo en una reclamación.</description>
        <label>Fecha ultima notificación espera documen</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Claim/fields/CS_correoReclamante__c.field-meta.xml
<CustomField>
    <fullName>CS_correoReclamante__c</fullName>
    <label>Correo electrónico Reclamante</label>
    <type>Email</type>
</CustomField>

DeploysDevSP2/objects/SuspendedNotificationConfiguration__mdt.object
<CustomObject>
    <description>Configuración de campo para la frecuencia de notificación de correo en espera de documentos.</description>
    <label>Configuración notificacion suspendido</label>
    <pluralLabel>Configuración notificaciones suspendido</pluralLabel>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Configuración de campo para mapear la frecuencia de notificación en días.</description>
        <inlineHelpText>Ingresar valor en números ,  valor que sera tomado como rango de tiempo en días para envió de notificación.</inlineHelpText>
        <label>Frecuencia</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NotificationValidity__c</fullName>
        <description>Configuración de campo para mapear la frecuencia de notificación en días.</description>
        <inlineHelpText>Ingresar valor en números ,  valor que sera tomado como rango de tiempo en Años para envió de notificación.</inlineHelpText>
        <label>Vigencia de notificación</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SendNotificationWaitingDocumentBatchTest.cls
/**
 * @description       : 
 * @author            : diego.jacanamijoy@oc.vasscompany.com
 * @group             : 
 * @last modified on  : 12-06-2024
 * @last modified by  : diego.jacanamijoy@oc.vasscompany.com
**/
@IsTest
public with sharing class SendNotificationWaitingDocumentBatchTest {

    static SuspendedNotificationConfiguration__mdt notificationSetting = SuspendedNotificationConfiguration__mdt.getInstance('NotifySuspended');

    static Date dateNotification = Date.today().addDays(Integer.valueOf(-notificationSetting.Frequency__c));
    static Date dateNotNotification = Date.today().addYears(Integer.valueOf(-notificationSetting.NotificationValidity__c)).addDays(1);
    
    @TestSetup
    static void makeData(){

        Claim testClaim = new Claim(
            Name = 'test claim',
            Status = 'Suspendido',
            ClaimEmail__c = 'testemail@test.com',
            CS_correoReclamante__c = 'testemail@test.com',
            LastNotificationDateWaitingForDocument__c = System.today().addDays(-10)
        );
        insert testClaim;
        
        // Create a ClaimCoverage record with the necessary fields for testing
        ClaimCoverage cc = new ClaimCoverage(
            CS_ClaimEmail__c = 'testemail@test.com',
            Status = 'Suspendido',
            CS_SubStatus__c = 'Documentos Solicitados',
            LastNotificationDateWaitingForDocument__c = dateNotification,
            FirstNotificationDateWaitingForDocument__c = dateNotNotification,
            Name = 'Test',
            ClaimId = testClaim.Id,
            InternalReserveMode = 'CoverageReserve'
        );

        insert cc;

        cc.CS_ClaimEmail__c = 'testemail@test.com';
        update cc;

    }

    @IsTest
    static void sendNotificationTest() {
        Claim testCoverageClaim = [SELECT Id, ClaimEmail__c FROM Claim LIMIT 1];
        //System.assertNotEquals(null, testCoverageClaim.ClaimEmail__c, 'ClaimEmail__c should not be null');

        // Verify that the test data has been set up correctly
        ClaimCoverage testCoverage = [SELECT Id, CS_ClaimEmail__c, Name, CS_SubStatus__c FROM ClaimCoverage LIMIT 1];
        System.assertNotEquals(null, testCoverage.CS_ClaimEmail__c, 'CS_ClaimEmail__c should not be null');

        Test.startTest();
            Id jobid = Database.executeBatch(new SendNotificationWaitingDocumentsBatch(), 5);
        Test.stopTest();

        ClaimCoverage updatedClaim = [SELECT LastNotificationDateWaitingForDocument__c FROM ClaimCoverage LIMIT 1];
        System.assertEquals(System.today(), updatedClaim.LastNotificationDateWaitingForDocument__c, 'It´s not the expected date');
    }

    @IsTest
    static void testSchedule() {
        Test.startTest();
            String CRON_EXP = '0 6 * * * ?';
            String jobId = system.schedule('Test status', CRON_EXP, new SendNotificationWaitingDocumentsBatch());
        Test.stopTest();

        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression, 'The cron expression is not the expected');
        System.assertEquals(0, ct.TimesTriggered, 'The TimesTriggered is not the expected');
    }
}