DeploysDevSP2/objects/Claim.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>CS_SubEstado__c</fullName>
        <description>Sub Estado del estado actual</description>
        <label>Sub Estado</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Nuevo</fullName>
                </value>
                <value>
                    <fullName>Pago Rechazado</fullName>
                </value>
                <value>
                    <fullName>En Aprobación</fullName>
                </value>
                <value>
                    <fullName>Documentos Solicitados</fullName>
                </value>
                <value>
                    <fullName>Documentos Adicionales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClaimEmail__c</fullName>
        <description>Email del asegurado de una reclamación</description>
        <label>ClaimEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstNotificationDateWaitingForDocument__c</fullName>
        <description>Campo que almacena la primera fecha de notificación</description>
        <label>Fecha primer notificación espera docs</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastNotificationDateWaitingForDocument__c</fullName>
        <description>Campo que se crea para almacenar la ultima fecha de notificación de envió de correo en una reclamación.</description>
        <label>Fecha ultima notificación espera documen</label>
        <type>Date</type>
    </fields>
</CustomObject>

DeploysDevSP2/objects/SuspendedNotificationConfiguration__mdt.object
<CustomObject>
    <description>Configuración de campo para la frecuencia de notificación de correo en espera de documentos.</description>
    <label>Configuración notificacion suspendido</label>
    <pluralLabel>Configuración notificaciones suspendido</pluralLabel>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Configuración de campo para mapear la frecuencia de notificación en días.</description>
        <inlineHelpText>Ingresar valor en números ,  valor que sera tomado como rango de tiempo en días para envió de notificación.</inlineHelpText>
        <label>Frecuencia</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NotificationValidity__c</fullName>
        <description>Configuración de campo para mapear la frecuencia de notificación en días.</description>
        <inlineHelpText>Ingresar valor en números ,  valor que sera tomado como rango de tiempo en Años para envió de notificación.</inlineHelpText>
        <label>Vigencia de notificación</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

DeploysDevSP2/classes/SendNotificationWaitingDocumentsBatch.cls
/**
 * @description       : 
 * @author            : diego.jacanamijoy@oc.vasscompany.com
 * @group             : 
 * @last modified on  : 12-14-2023
 * @last modified by  : diego.jacanamijoy@oc.vasscompany.com
**/
public with sharing class SendNotificationWaitingDocumentsBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable {

    public static final String EMAIL_TEMPLATE_NAME = 'Email Template Status Suspended';

    public Database.QueryLocator start(Database.BatchableContext bc) {

        //Metodo para extraer la informacion de la metada valor de la fecuencia en dias.
        SuspendedNotificationConfiguration__mdt notificationSetting = SuspendedNotificationConfiguration__mdt.getInstance('NotifySuspended');

        //Se realiza la validacion de calcular ala fecha actual restarle el valor de la frecuencia en dias.
        Date dateNotification = Date.today().addDays(Integer.valueOf(-notificationSetting.Frequency__c));
        Date dateNotNotification = Date.today().addYears(Integer.valueOf(-notificationSetting.NotificationValidity__c));

        //Select que permite extraer la informacion del Claim 
            String query = 'SELECT ClaimEmail__c  FROM Claim WHERE Status = \'Suspendido\' AND CS_SubEstado__c = \'Documentos Solicitados\'';
 			query += 'AND LastNotificationDateWaitingForDocument__c =: dateNotification AND FirstNotificationDateWaitingForDocument__c >: dateNotNotification';
        return Database.getQueryLocator(query);
        
    }

    public void execute(Database.BatchableContext bc, List<sObject> records){
        // process each batch of records
        SendEmailHelper.sendMassEmails(EMAIL_TEMPLATE_NAME, 'ClaimEmail__c', records);
    }

    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
    
    public void execute(SchedulableContext sc) {
      SendNotificationWaitingDocumentsBatch batch = new SendNotificationWaitingDocumentsBatch(); 
      Database.executeBatch(batch);
   }
}